# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, archive, conduit, resourcet, transformers }:

cabal.mkDerivation (self: {
  pname = "libarchive-conduit";
  version = "0.1.0.0";
  sha256 = "022fnxxwz44cjzcldk3yg1xs77xqnrvkr9bv6hi7kdy120dk4p04";
  buildDepends = [ conduit resourcet transformers ];
  extraLibraries = [ archive ];
  meta = {
    description = "Read many archive formats with libarchive and conduit";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
